create table if not exists public.stocklens_portfolios (
  client_id text primary key,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.stocklens_portfolios enable row level security;

grant select, insert, update, delete on public.stocklens_portfolios to service_role;

drop policy if exists stocklens_portfolios_deny_anon_select on public.stocklens_portfolios;
drop policy if exists stocklens_portfolios_deny_anon_insert on public.stocklens_portfolios;
drop policy if exists stocklens_portfolios_deny_anon_update on public.stocklens_portfolios;

create policy stocklens_portfolios_deny_anon_select
  on public.stocklens_portfolios
  for select
  to anon, authenticated
  using (false);

create policy stocklens_portfolios_deny_anon_insert
  on public.stocklens_portfolios
  for insert
  to anon, authenticated
  with check (false);

create policy stocklens_portfolios_deny_anon_update
  on public.stocklens_portfolios
  for update
  to anon, authenticated
  using (false)
  with check (false);

create index if not exists stocklens_portfolios_updated_at_idx
  on public.stocklens_portfolios (updated_at desc);

comment on table public.stocklens_portfolios is
  'Server-side portfolio backup for CAN SLIM stock scanner. Access through server API with Supabase service role key only.';

create table if not exists public.stocklens_analysis_snapshots (
  id bigint generated by default as identity primary key,
  ticker text not null,
  market text not null default 'us',
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.stocklens_analysis_snapshots enable row level security;

grant select, insert, delete on public.stocklens_analysis_snapshots to service_role;

drop policy if exists stocklens_analysis_snapshots_deny_anon_select on public.stocklens_analysis_snapshots;
drop policy if exists stocklens_analysis_snapshots_deny_anon_insert on public.stocklens_analysis_snapshots;

create policy stocklens_analysis_snapshots_deny_anon_select
  on public.stocklens_analysis_snapshots
  for select
  to anon, authenticated
  using (false);

create policy stocklens_analysis_snapshots_deny_anon_insert
  on public.stocklens_analysis_snapshots
  for insert
  to anon, authenticated
  with check (false);

create index if not exists stocklens_analysis_snapshots_ticker_created_idx
  on public.stocklens_analysis_snapshots (ticker, created_at desc);

comment on table public.stocklens_analysis_snapshots is
  'Server-side score and signal snapshots for tracking daily scanner changes.';

create table if not exists public.stocklens_scanned_stocks (
  ticker text primary key,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.stocklens_scanned_stocks enable row level security;

grant select, insert, update, delete on public.stocklens_scanned_stocks to service_role;

drop policy if exists stocklens_scanned_stocks_deny_anon_select on public.stocklens_scanned_stocks;
drop policy if exists stocklens_scanned_stocks_deny_anon_insert on public.stocklens_scanned_stocks;
drop policy if exists stocklens_scanned_stocks_deny_anon_update on public.stocklens_scanned_stocks;

create policy stocklens_scanned_stocks_deny_anon_select
  on public.stocklens_scanned_stocks
  for select
  to anon, authenticated
  using (false);

create policy stocklens_scanned_stocks_deny_anon_insert
  on public.stocklens_scanned_stocks
  for insert
  to anon, authenticated
  with check (false);

create policy stocklens_scanned_stocks_deny_anon_update
  on public.stocklens_scanned_stocks
  for update
  to anon, authenticated
  using (false)
  with check (false);

create index if not exists stocklens_scanned_stocks_updated_at_idx
  on public.stocklens_scanned_stocks (updated_at desc);

comment on table public.stocklens_scanned_stocks is
  'Recently scanned ticker summaries persisted for the Vercel deployment. Access through server API with Supabase service role key only.';

create table if not exists public.stocklens_watchlists (
  client_id text primary key,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.stocklens_watchlists enable row level security;

grant select, insert, update, delete on public.stocklens_watchlists to service_role;

drop policy if exists stocklens_watchlists_deny_anon_select on public.stocklens_watchlists;
drop policy if exists stocklens_watchlists_deny_anon_insert on public.stocklens_watchlists;
drop policy if exists stocklens_watchlists_deny_anon_update on public.stocklens_watchlists;

create policy stocklens_watchlists_deny_anon_select
  on public.stocklens_watchlists
  for select
  to anon, authenticated
  using (false);

create policy stocklens_watchlists_deny_anon_insert
  on public.stocklens_watchlists
  for insert
  to anon, authenticated
  with check (false);

create policy stocklens_watchlists_deny_anon_update
  on public.stocklens_watchlists
  for update
  to anon, authenticated
  using (false)
  with check (false);

create index if not exists stocklens_watchlists_updated_at_idx
  on public.stocklens_watchlists (updated_at desc);

comment on table public.stocklens_watchlists is
  'Per-browser watchlist tickers persisted for the scanner. Access through server API with local client token.';
